/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package serverManagementConsol;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author Roy
 */
public class KittyMiningBuddyManagementConsol extends javax.swing.JFrame {
    
    private KMBMCSettings objSettings = null;

    /**
     * Creates new form KittyMiningBuddyManagementConsol
     */
    public KittyMiningBuddyManagementConsol() {
        initComponents();
        this.initialise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnMainDisplay = new javax.swing.JTabbedPane();
        connStatusPanel2 = new kittyMiningBuddyLibrary.ConnStatusPanel();
        mnuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuConnect = new javax.swing.JMenuItem();
        mnuDisconnect = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuConnect.setText("Connect");
        jMenu1.add(mnuConnect);

        mnuDisconnect.setText("Disconnect");
        jMenu1.add(mnuDisconnect);
        jMenu1.add(jSeparator1);

        mnuExit.setText("Exit");
        jMenu1.add(mnuExit);

        mnuBar.add(jMenu1);

        jMenu2.setText("Edit");
        mnuBar.add(jMenu2);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnMainDisplay)
            .addComponent(connStatusPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(connStatusPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(tpnMainDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KittyMiningBuddyManagementConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KittyMiningBuddyManagementConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KittyMiningBuddyManagementConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KittyMiningBuddyManagementConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new KittyMiningBuddyManagementConsol().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private kittyMiningBuddyLibrary.ConnStatusPanel connStatusPanel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuConnect;
    private javax.swing.JMenuItem mnuDisconnect;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JTabbedPane tpnMainDisplay;
    // End of variables declaration//GEN-END:variables

    private void initialise(){
        this.objSettings = new KMBMCSettings();
        this.objSettings.addPropertyChangeListener(new ConnectionStatusChangeListener());
    }
    
    private class ConnectionStatusChangeListener implements PropertyChangeListener{

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if(null != objSettings && evt.getPropertyName().equalsIgnoreCase("ConnStatus")){
                switch(objSettings.getConnStatus()){
                    case CONNECTED:
                        break;
                    case DISCONNECTED:
                        break;
                }
            }
        }
    }
}
