/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kittyMiningBuddyLibrary;

import java.awt.Color;
import kittyMiningBuddyLibrary.enums.ConnectStatus;

/**
 *
 * @author Roy
 */
public class ConnStatusPanel extends javax.swing.JPanel {
    
    private ConnectStatus status = ConnectStatus.DISCONNECTED;

    /**
     * Creates new form ConnStatusPanel
     */
    public ConnStatusPanel() {
        initComponents();
        this.setupDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMsg = new javax.swing.JLabel();

        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsg.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMsg;
    // End of variables declaration//GEN-END:variables

    public void setConnectionStatus(ConnectStatus enuNewStatus){
        this.status = enuNewStatus;
        this.setupDisplay();
    }
    
    private void setupDisplay(){
        lblMsg.setText(status.toString());
        switch(status){
            case CONNECTED:
                lblMsg.setBackground(Color.GREEN);
                this.setBackground(Color.GREEN);
                lblMsg.setForeground(Color.WHITE);
                break;
            case DISCONNECTED:
                lblMsg.setBackground(Color.RED);
                this.setBackground(Color.RED);
                lblMsg.setForeground(Color.WHITE);
                break;
        }
    }

}
