/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kittyminingbuddy.client;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import kittyMiningBuddyLibrary.MiningBuddyServerDetails;

/**
 *
 * @author Roy
 */
public class ServerDetails extends javax.swing.JFrame {
    
    private KMBSettings objSettings = null;

    /**
     * Creates new form ServerDetails
     */
    public ServerDetails() {
        initComponents();
        this.initialise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServerAddress = new javax.swing.JLabel();
        txtServerInternetAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        spnPortNo = new javax.swing.JSpinner();
        btnSaveServerDetails = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        lblServerAddress.setText("Server Web Address");

        txtServerInternetAddress.setText("ENTER SERVER ADDRESS");

        jLabel1.setText("Server Port Number");

        spnPortNo.setModel(new javax.swing.SpinnerNumberModel(15000, 10000, 65536, 1));

        btnSaveServerDetails.setText("Save Server Details");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_Click(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lblServerAddress))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServerInternetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnPortNo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveServerDetails)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServerAddress)
                    .addComponent(txtServerInternetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnPortNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveServerDetails)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancel_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_Click
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancel_Click

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ServerDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveServerDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblServerAddress;
    private javax.swing.JSpinner spnPortNo;
    private javax.swing.JTextField txtServerInternetAddress;
    // End of variables declaration//GEN-END:variables

    public void setSettings(KMBSettings objNewSettings){
        this.objSettings = objNewSettings;
    }
    
    private void initialise(){
        this.addWindowListener(new WindowActivatedListener());
    }
    
    private class WindowActivatedListener extends WindowAdapter
    {

        @Override
        public void windowActivated(WindowEvent e) {
            if(null != objSettings){
                MiningBuddyServerDetails serverDetails = objSettings.getServerDetails();
                txtServerInternetAddress.setText(serverDetails.getInternetAddress().getHostAddress());
                spnPortNo.setValue(serverDetails.getPort());
                switch(objSettings.getConnectionStatus()){
                    case CONNECTED:
                        txtServerInternetAddress.setEnabled(false);
                        spnPortNo.setEnabled(false);
                        btnSaveServerDetails.setEnabled(false);
                        break;
                    case DISCONNECTED:
                        txtServerInternetAddress.setEnabled(true);
                        spnPortNo.setEnabled(true);
                        btnSaveServerDetails.setEnabled(true);
                        break;
                }
            }
        }
        
    }
}
